trigger:
    - master

pool:
    vmImage: 'ubuntu-latest'

variables:
    npm_config_cache: '$(Pipeline.Workspace)/.npm'

steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      target: host
      displayName: Install Node.js

    # - task: Cache@2
    #   inputs:
    #     key: 'npm | $(Build.SourcesDirectory)/package-lock.json'
    #     path: $(Build.SourcesDirectory)/node_modules
    #     cacheHitVar: CACHE_RESTORED
    #   displayName: Cache npm
    - script: which node
    - script: echo `pwd`
    - script: ls -la
    - script: ls '$(Pipeline.Workspace)'
    - script: ls '$(Build.SourcesDirectory)'
    - script: npm ci
      workingDirectory: '$(Build.SourcesDirectory)'
      displayName: 'npm ci'
    # - task: Npm@1
    #   inputs:
    #     command: 'ci'
    #   # condition: ne(variables.CACHE_RESTORED, 'true')
    #   displayName: Install project dependencies

    - script: |
        git config --global user.email "bot@trustwallet.com"
        git config --global user.name "TrustWalletBot"
    - checkout: self
      persistCredentials: true

    - script: npm run checksum-erc20

    - task: ShellScript@2
      inputs:
        scriptPath: './script/commit.sh'
        failOnStandardError: true
      target: host

    - script: npm t
      displayName: "Run tests"