trigger:
    - master

pool:
    vmImage: 'ubuntu-latest'

variables:
    npm_config_cache: '$(Pipeline.Workspace)/.npm'

steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: Install Node.js

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package-lock.json'
        path: $(npm_config_cache)
      displayName: Cache npm

    - script: npm ci --cache $(npm_config_cache)

    - script: npm t