trigger:
    - master

pool:
    vmImage: 'ubuntu-16.04'

variables:
    npm_config_cache: '$(Pipeline.Workspace)/.npm'

steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: Install Node.js
    
    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package-lock.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
          npm
        path: $(npm_config_cache)
      continueOnError: true
      displayName: Cache npm
    
    - script: npm ci --cache $(npm_config_cache)

    - script: |
        git config --global user.email "bot@trustwallet.com"
        git config --global user.name "TrustWalletBot"
    - checkout: self
      persistCredentials: true

    - script: npm run checksum-erc20

    - task: ShellScript@2
      inputs:
        scriptPath: './script/commit.sh'
        failOnStandardError: true
      
    - script: npm t