name: Pull Request CI
on:
    push:
      branches:
        - '*'
        - '!master'
    pull_request:
      branches: [master]
jobs:
  pull_request_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache node modules
      uses: actions/cache@v1
      id: npm-cache
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      # if: steps.npm-cache.outputs.cache-hit == 'false'
      run: npm ci
    - name: Run test
      run: npm t