name: Pull Request CI
on:
    push:
      branches:
        - '*'
        - '!master'
    pull_request:
      branches: [master]
jobs:
  pull_request_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/setup-node@v1
    #   with:
    #     node-version: '12.x'
    # - uses: bahmutov/npm-install@v1
    # - run: npm t
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '*' --include './blockchains'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1