name: Upload to IPFS
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  upload-ipfs:
    runs-on: ubuntu-latest
    steps:
      - uses: aquiladev/ipfs-action@v0.1.5
        id: ipfs-test-bc
        with:
          path: ./blockchains
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          pinataPinName: blockchains
          verbose: false
      - uses: aquiladev/ipfs-action@v0.1.5
        id: ipfs-test
        with:
          path: ./dapps
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          pinataPinName: dapps
          verbose: false
